version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            cd src/frontend
            sudo docker build -t haseebh/frontend:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push haseebh/frontend:${CIRCLE_BUILD_NUM}
            #curl --request POST -H "Content-Type: application/json" --data '{"image_name":"haseebh/frontend","image_tag": "'"${CIRCLE_BUILD_NUM}"'" , "type":"container", "projects":["demo-dry-run-p1"]}' https://sapis.cloudplex.cf/cp-next-gen-cd/api/v1/cpcd
      - run:
          name: Build and push Docker image
          command: |
            cd src/productcatalogservice
            sudo docker build -t haseebh/productcatalogservice:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push haseebh/productcatalogservice:${CIRCLE_BUILD_NUM}
            #curl --request POST -H "Content-Type: application/json" --data '{"image_name":"haseebh/productcatalogservice","image_tag": "'"${CIRCLE_BUILD_NUM}"'" , "type":"container", "projects":["demo-dry-run-p1"]}' https://sapis.cloudplex.cf/cp-next-gen-cd/api/v1/cpcd
      - run:
          name: Build and push Docker image
          command: |
            cd src/storageservice
            sudo docker build -t haseebh/storageservice:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push haseebh/storageservice:${CIRCLE_BUILD_NUM}
            #curl --request POST -H "Content-Type: application/json" --data '{"image_name":"haseebh/storageservice","image_tag": "'"${CIRCLE_BUILD_NUM}"'" , "type":"container", "projects":["demo-dry-run-p1"]}' https://sapis.cloudplex.cf/cp-next-gen-cd/api/v1/cpcd
      - run:
          name: Build and push Docker image
          command: |
            cd src/shippingservice
            sudo docker build -t haseebh/shippingservice:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push haseebh/shippingservice:${CIRCLE_BUILD_NUM}
            #curl --request POST -H "Content-Type: application/json" --data '{"image_name":"haseebh/shippingservice","image_tag": "'"${CIRCLE_BUILD_NUM}"'" , "type":"container", "projects":["demo-dry-run-p1"]}' https://sapis.cloudplex.cf/cp-next-gen-cd/api/v1/cpcd